name: typecheck

# on:
#   pull_request:
#     branches:
#       - develop
#       - master

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: frontend

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          # package.json/engines/node と同じ値にすること
          node-version: 21.6.1
      - name: Install Yarn
        run: npm install -g yarn
      - uses: actions/cache@v4
        id: frontend_node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - run: echo '${{ toJSON(steps.frontend_node_modules_cache_id.outputs) }}'
      - if: ${{ steps.frontend_node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: yarn install

  my-job:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          # package.json/engines/node と同じ値にすること
          node-version: 21.6.1
      - name: Install Yarn
        run: npm install -g yarn
      - uses: actions/cache@v4
        id: frontend_node_modules_cache_id
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - run: echo '${{ toJSON(steps.frontend_node_modules_cache_id.outputs) }}'
      - if: ${{ steps.frontend_node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: yarn install
      - name: Run TypeCheck
        run: yarn tsc
